import nodemailer from 'nodemailer';

export const sendApplicationNotificationEmail = async ({
    recruiterEmail,
    recruiterName,
    jobTitle,
    applicantName,
    applicantEmail,
    applicantPhone,
    coverLetter,
    resumeUrl,
    resumeFilePath,
}) => {
    try {
        const smtpHost = process.env.SMTP_HOST;
        const smtpUser = process.env.SMTP_USER;
        const smtpPass = process.env.SMTP_PASS;

        // Skip sending actual email if SMTP credentials are missing or default
        if (!smtpHost || !smtpUser || smtpUser === 'your_email@gmail.com') {
            console.log(`[Email Service Simulation] Notification for job "${jobTitle}" application by ${applicantName} (${applicantEmail}) logged.`);
            return { success: true, simulated: true };
        }

        const transporter = nodemailer.createTransport({
            host: smtpHost,
            port: Number(process.env.SMTP_PORT) || 587,
            secure: Number(process.env.SMTP_PORT) === 465,
            auth: {
                user: smtpUser,
                pass: smtpPass,
            },
        });

        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
                <div style="background-color: #7c3aed; color: #ffffff; padding: 20px; text-align: center;">
                    <h2 style="margin: 0;">New Job Application Received!</h2>
                    <p style="margin: 5px 0 0 0; font-size: 14px;">Sakhi Career Opportunities</p>
                </div>
                <div style="padding: 24px; color: #333333;">
                    <p>Dear <strong>${recruiterName || 'Hiring Team'}</strong>,</p>
                    <p>You have received a new application for the position of <strong>${jobTitle}</strong>.</p>
                    
                    <div style="background-color: #f5f3ff; border-left: 4px solid #7c3aed; padding: 16px; margin: 20px 0; border-radius: 4px;">
                        <h4 style="margin: 0 0 10px 0; color: #6d28d9;">Applicant Information</h4>
                        <p style="margin: 4px 0;"><strong>Name:</strong> ${applicantName}</p>
                        <p style="margin: 4px 0;"><strong>Email:</strong> <a href="mailto:${applicantEmail}">${applicantEmail}</a></p>
                        <p style="margin: 4px 0;"><strong>Phone:</strong> ${applicantPhone}</p>
                        <p style="margin: 4px 0;"><strong>Application Date:</strong> ${new Date().toLocaleDateString('en-IN')}</p>
                    </div>

                    ${coverLetter ? `
                        <div style="margin-bottom: 20px;">
                            <h4 style="margin: 0 0 6px 0; color: #4b5563;">Cover Letter:</h4>
                            <div style="background-color: #f9fafb; padding: 12px; border-radius: 6px; font-style: italic; white-space: pre-wrap;">${coverLetter}</div>
                        </div>
                    ` : ''}

                    ${resumeUrl ? `
                        <p style="margin-top: 20px;">
                            <a href="${resumeUrl}" style="background-color: #7c3aed; color: #ffffff; padding: 10px 20px; text-decoration: none; border-radius: 6px; display: inline-block;">Download Resume</a>
                        </p>
                    ` : ''}

                    <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
                    <p style="font-size: 12px; color: #888888; text-align: center;">
                        This email was automatically generated by Sakhi Career Portal.
                    </p>
                </div>
            </div>
        `;

        const mailOptions = {
            from: process.env.FROM_EMAIL || `"Sakhi Careers" <${smtpUser}>`,
            to: recruiterEmail,
            subject: `[Sakhi Careers] New Application for ${jobTitle} - ${applicantName}`,
            html: htmlContent,
            attachments: resumeFilePath ? [{ path: resumeFilePath }] : [],
        };

        const info = await transporter.sendMail(mailOptions);
        console.log(`[Email Service] Application notification sent to ${recruiterEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error) {
        console.error('[Email Service Error]:', error.message);
        return { success: false, error: error.message };
    }
};
